{% set name = "entwine" %}
{% set version = "3.0.0" %}
{% set sha256 = "1092653a40ffa09637863f39fa7f085f86f1bbfbdd413787f8ed932dc5aebb05" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/connormanning/entwine/archive/{{ version }}.zip
  sha256: {{ sha256 }}

build:
  number: 6
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - pdal 2.5
    - xz
    - curl
    - openssl
  run:
    - pdal 2.5
    - xz
    - curl
    - openssl
test:
  commands:
    - entwine --version

about:
  home: https://entwine.io
  license: LGPL-2.1-or-later
  license_file: LICENSE.txt
  summary: 'Point cloud spatial indexing library'

  description: |
    Entwine is a C/C++ library for organizing point clouds as a
    octree tile structure.
  doc_url: https://entwine.io
  dev_url: https://github.com/connormanning/entwine

extra:
  recipe-maintainers:
    - hobu
    - connormanning
    - chambbj
