{% set name = "entwine" %}
{% set version = "3.1.1" %}
{% set sha256 = "ac7869d43df8acfae28652c989791ad6ad0c2c437b3bd591a1142db44c26bd01" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/connormanning/entwine/archive/{{ version }}.zip
  sha256: {{ sha256 }}

build:
  number: 1
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - ninja
  host:
    - pdal
    - curl
    - openssl
  run:
    - pdal
    - curl
    - openssl
test:
  commands:
    - entwine --version

about:
  home: https://entwine.io
  license: LGPL-2.1-or-later
  license_file: LICENSE.txt
  summary: 'Point cloud spatial indexing library'

  description: |
    Entwine is a C/C++ library for organizing point clouds as a
    octree tile structure.
  doc_url: https://entwine.io
  dev_url: https://github.com/connormanning/entwine

extra:
  recipe-maintainers:
    - hobu
    - connormanning
    - chambbj
