schema_version: 1

context:
  name: entwine
  version: 3.1.1
  sha256: ac7869d43df8acfae28652c989791ad6ad0c2c437b3bd591a1142db44c26bd01

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/connormanning/entwine/archive/${{ version }}.zip
  sha256: ${{ sha256 }}

build:
  number: 7
  skip: ppc64le

requirements:
  build:
    - ${{ stdlib("c") }}
    - ${{ compiler('cxx') }}
    - cmake
    - make
    - ninja
  host:
    - libpdal-core
    - curl
    - openssl
  run:
    - libpdal-core
    - curl
    - openssl

tests:
  - script:
      - entwine --version

about:
  license: LGPL-2.1-or-later
  license_file: LICENSE.txt
  summary: Point cloud spatial indexing library
  description: |
    Entwine is a C/C++ library for organizing point clouds as a
    octree tile structure.
  homepage: https://entwine.io
  repository: https://github.com/connormanning/entwine
  documentation: https://entwine.io

extra:
  recipe-maintainers:
    - hobu
    - connormanning
    - chambbj
