travis:
  secure:
    BINSTAR_TOKEN: Foa9ysv7i+ryUAcanHC6p0HlhCB+0WMvbsg3BLJKuXVH/5bDe5XwB2d42IrHMFEA9pefzwrsFRiXIGN9RVowF52lrFWWzNmxyzLuSzqfZ9pq3AWIVUTOB5m1Pz2dF25MfR4Dfz1Q07UZ0cGaXl4Hi56R2N4jWF1XxWuI5riGinbfNgitJihTnR25uJl4+14Y33r2F2swBvt++lkcXCeCFZjOchAkLejfXbukigbCQDoUEI6sU2fIKtDh30xokn1pQKThhWMqTsG04qAJ5MdCuCfQ10A7M2NyinH3IgZUslfYuYuMR6ie9nLjJti0TjNTCZPrdDw8otg+i+PIw0ZzHh61a5qcVG/gv7Z+AxarDV3HagVWk8PLdetU6kBaOdBattYIMkrCYdaZ0dvI8PHIl9KqAqs6LBjYg5pjnOplrHQ7qouvj0UbP7Il5mrLpyh5pxCF5mr1UewycC62vefFpD605ihG6B/RhHAPV/WQr7eKc8qckypjSa0BxdEs+kqcEJ9ABBNcCzDPoX1BiszmT26D4Hbu5NtP25VMYJNAh12VsEGsn/kx5GPIBMzviFPb8AfDHAaF8Ez76AYqu80iWf9BWVR+pNB4OFuKI2/z5aTPtQ8jpxrrvMpUTIs3d1FVGS2UVKbdx9CObIzt3D0y2DHOhhAdCPODNcQ2LXHtKXY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
